//! Retrieval with RRF fusion across multiple channels.
//!
//! Channels:
//! - FTS5: full-text search on title + content
//! - Key: exact content_key lookup
//! - Vector: semantic similarity via `navra-rag` ChunkStore (requires `rag` feature)
//! - HyDE: hypothetical document embeddings (caller provides embedding)
//!
//! The vector channel requires a pre-computed query embedding. Use
//! [`MemoryRetriever::retrieve_with_embedding`] to supply one, or
//! [`MemoryRetriever::retrieve`] which skips the vector channel.

use crate::error::MemoryError;
use crate::knowledge::KnowledgeStore;
use crate::types::MemoryEntry;
use std::collections::HashMap;

#[cfg(feature = "rag")]
use {crate::types::MemoryType, std::sync::Arc};

/// A scored retrieval result.
#[derive(Debug, Clone)]
pub struct ScoredEntry {
    pub entry: MemoryEntry,
    pub score: f64,
}

/// Multi-channel retriever with Reciprocal Rank Fusion.
pub struct MemoryRetriever<'a> {
    store: &'a KnowledgeStore,
    #[cfg(feature = "rag")]
    chunk_store: Option<Arc<navra_rag::ChunkStore>>,
}

impl<'a> MemoryRetriever<'a> {
    pub fn new(store: &'a KnowledgeStore) -> Self {
        Self {
            store,
            #[cfg(feature = "rag")]
            chunk_store: None,
        }
    }

    /// Attach a `ChunkStore` for vector similarity search.
    ///
    /// When set, the vector channel will query the chunk store using
    /// embeddings passed to [`Self::retrieve_with_embedding`].
    #[cfg(feature = "rag")]
    pub fn with_chunk_store(mut self, chunk_store: Arc<navra_rag::ChunkStore>) -> Self {
        self.chunk_store = Some(chunk_store);
        self
    }

    /// Retrieve top-N entries by fusing results from all channels with RRF.
    ///
    /// The vector channel is skipped (no embedding provided). Use
    /// [`Self::retrieve_with_embedding`] to include vector results.
    ///
    /// RRF score = sum(1 / (k + rank)) across channels, where k = 60.
    pub fn retrieve(&self, query: &str, top_n: usize) -> Result<Vec<ScoredEntry>, MemoryError> {
        self.retrieve_inner(query, None, None, top_n)
    }

    /// Retrieve top-N entries, including vector similarity via `query_embedding`.
    ///
    /// The caller is responsible for computing the embedding from the query
    /// text using whatever model is appropriate (e.g. via `navra-model`).
    pub fn retrieve_with_embedding(
        &self,
        query: &str,
        query_embedding: &[f32],
        top_n: usize,
    ) -> Result<Vec<ScoredEntry>, MemoryError> {
        self.retrieve_inner(query, Some(query_embedding), None, top_n)
    }

    /// Retrieve top-N entries with both direct and HyDE vector channels.
    ///
    /// `query_embedding` is the direct embedding of the query text.
    /// `hyde_embedding` is the embedding of a hypothetical ideal answer
    /// generated by an LLM. HyDE embeddings are closer to stored answers
    /// than question embeddings, improving recall for question-style queries.
    ///
    /// The caller generates the hypothetical document and embeds it:
    /// 1. LLM: "What document would answer: {query}?" → hypothetical_doc
    /// 2. Embed hypothetical_doc → hyde_embedding
    pub fn retrieve_with_hyde(
        &self,
        query: &str,
        query_embedding: &[f32],
        hyde_embedding: &[f32],
        top_n: usize,
    ) -> Result<Vec<ScoredEntry>, MemoryError> {
        self.retrieve_inner(query, Some(query_embedding), Some(hyde_embedding), top_n)
    }

    fn retrieve_inner(
        &self,
        query: &str,
        query_embedding: Option<&[f32]>,
        hyde_embedding: Option<&[f32]>,
        top_n: usize,
    ) -> Result<Vec<ScoredEntry>, MemoryError> {
        let k = 60.0_f64;

        // Channel 1: FTS5
        let fts_results = self.store.search(query)?;
        // Channel 2: exact key lookup (treat query as potential content_key)
        let key_results = self.channel_key(query)?;
        // Channel 3: vector
        let vector_results = self.channel_vector(query_embedding)?;
        // Channel 4: HyDE (hypothetical document embedding)
        let hyde_results = self.channel_hyde(hyde_embedding)?;

        // Collect all channels: Vec<Vec<MemoryEntry>>
        let channels: Vec<Vec<MemoryEntry>> =
            vec![fts_results, key_results, vector_results, hyde_results];

        // Fuse with RRF: accumulate scores by entry id, keep first entry seen.
        let mut scores: HashMap<String, f64> = HashMap::new();
        let mut entries: HashMap<String, MemoryEntry> = HashMap::new();

        for channel in &channels {
            for (rank, entry) in channel.iter().enumerate() {
                let rrf_score = 1.0 / (k + rank as f64 + 1.0);
                *scores.entry(entry.id.clone()).or_insert(0.0) += rrf_score;
                entries
                    .entry(entry.id.clone())
                    .or_insert_with(|| entry.clone());
            }
        }

        // Sort by descending score
        let mut results: Vec<ScoredEntry> = scores
            .into_iter()
            .filter_map(|(id, score)| {
                entries
                    .remove(&id)
                    .map(|entry| ScoredEntry { entry, score })
            })
            .collect();
        results.sort_by(|a, b| {
            b.score
                .partial_cmp(&a.score)
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        results.truncate(top_n);

        Ok(results)
    }

    fn channel_key(&self, query: &str) -> Result<Vec<MemoryEntry>, MemoryError> {
        match self.store.query_by_key(query) {
            Ok(Some(entry)) => Ok(vec![entry]),
            Ok(None) => Ok(vec![]),
            Err(e) => Err(e),
        }
    }

    /// Vector similarity channel.
    ///
    /// When the `rag` feature is enabled and a `ChunkStore` is attached,
    /// searches for chunks similar to `query_embedding` and converts them
    /// to `MemoryEntry` values. Each chunk becomes a `MemoryType::Fact`
    /// entry with the chunk path as title and chunk content as content.
    ///
    /// Returns empty if no chunk store is set, no embedding is provided,
    /// or the `rag` feature is disabled.
    fn channel_vector(
        &self,
        _query_embedding: Option<&[f32]>,
    ) -> Result<Vec<MemoryEntry>, MemoryError> {
        #[cfg(feature = "rag")]
        if let (Some(cs), Some(embedding)) = (&self.chunk_store, _query_embedding) {
            let results = cs
                .search(embedding, 20)
                .map_err(|e| MemoryError::Other(format!("vector search failed: {e}")))?;
            let entries = results
                .into_iter()
                .map(|r| MemoryEntry {
                    id: format!("rag:{}:{}", r.path, r.chunk_index),
                    memory_type: MemoryType::Fact,
                    title: r.path,
                    content: r.content,
                    tags: vec![],
                    created_at: 0,
                    updated_at: None,
                })
                .collect();
            return Ok(entries);
        }
        Ok(vec![])
    }

    /// HyDE channel: search with the embedding of a hypothetical ideal answer.
    ///
    /// The caller generates a hypothetical document using an LLM and embeds
    /// it. This embedding is closer to stored answers than the raw query
    /// embedding, improving recall for question-style queries.
    fn channel_hyde(
        &self,
        _hyde_embedding: Option<&[f32]>,
    ) -> Result<Vec<MemoryEntry>, MemoryError> {
        #[cfg(feature = "rag")]
        if let (Some(cs), Some(embedding)) = (&self.chunk_store, _hyde_embedding) {
            let results = cs
                .search(embedding, 20)
                .map_err(|e| MemoryError::Other(format!("HyDE vector search failed: {e}")))?;
            let entries = results
                .into_iter()
                .map(|r| MemoryEntry {
                    id: format!("hyde:{}:{}", r.path, r.chunk_index),
                    memory_type: MemoryType::Fact,
                    title: r.path,
                    content: r.content,
                    tags: vec![],
                    created_at: 0,
                    updated_at: None,
                })
                .collect();
            return Ok(entries);
        }
        Ok(vec![])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::MemoryType;

    fn make_entry(id: &str, title: &str, content: &str) -> MemoryEntry {
        MemoryEntry {
            id: id.to_string(),
            memory_type: MemoryType::Fact,
            title: title.to_string(),
            content: content.to_string(),
            tags: vec![],
            created_at: 1000,
            updated_at: None,
        }
    }

    #[test]
    fn rrf_fusion_merges_channels() {
        let store = KnowledgeStore::open_memory().unwrap();
        // Insert entries that will appear in FTS
        store
            .store(&make_entry(
                "e1",
                "Rust language",
                "Rust is a systems programming language",
            ))
            .unwrap();
        store
            .store(&make_entry(
                "e2",
                "Rust ownership",
                "Ownership model in Rust",
            ))
            .unwrap();
        store
            .store(&make_entry(
                "e3",
                "Python language",
                "Python is interpreted",
            ))
            .unwrap();

        let retriever = MemoryRetriever::new(&store);
        let results = retriever.retrieve("Rust", 10).unwrap();

        // Should find the two Rust entries
        assert!(results.len() >= 2);
        // Scores should be positive
        for r in &results {
            assert!(r.score > 0.0);
        }
    }

    #[test]
    fn rrf_returns_empty_for_no_matches() {
        let store = KnowledgeStore::open_memory().unwrap();
        let retriever = MemoryRetriever::new(&store);
        let results = retriever.retrieve("nonexistent", 10).unwrap();
        assert!(results.is_empty());
    }

    #[test]
    #[cfg(feature = "rag")]
    fn rrf_vector_channel_with_chunk_store() {
        use std::sync::Arc;

        let store = KnowledgeStore::open_memory().unwrap();
        // Insert an FTS entry so we can verify vector results merge in
        store
            .store(&make_entry(
                "fts1",
                "Rust language",
                "Rust is a systems programming language",
            ))
            .unwrap();

        // Set up a ChunkStore with 4-dimensional embeddings
        let chunk_store = Arc::new(navra_rag::ChunkStore::open_memory(4).unwrap());
        let chunks = vec![navra_rag::chunk::Chunk {
            content: "Vector chunk about Rust".to_string(),
            start_byte: 0,
            end_byte: 22,
            index: 0,
            breadcrumb: None,
                section_start_byte: None,
                section_end_byte: None,
        }];
        let embeddings = vec![vec![1.0_f32, 0.0, 0.0, 0.0]];
        chunk_store
            .index_document("/rust.md", &chunks, &embeddings)
            .unwrap();

        let retriever = MemoryRetriever::new(&store).with_chunk_store(chunk_store);

        // Query with an embedding close to the indexed chunk
        let query_embedding = vec![0.9_f32, 0.1, 0.0, 0.0];
        let results = retriever
            .retrieve_with_embedding("Rust", &query_embedding, 10)
            .unwrap();

        // Should have the FTS entry plus the vector entry
        assert!(results.len() >= 2);
        let ids: Vec<&str> = results.iter().map(|r| r.entry.id.as_str()).collect();
        assert!(ids.contains(&"fts1"), "FTS entry should be present");
        assert!(
            ids.iter().any(|id| id.starts_with("rag:")),
            "Vector entry should be present with rag: prefix"
        );
    }

    #[test]
    #[cfg(feature = "rag")]
    fn rrf_hyde_channel_finds_different_results() {
        use std::sync::Arc;

        let store = KnowledgeStore::open_memory().unwrap();
        store
            .store(&make_entry(
                "fts1",
                "Security overview",
                "Auth tokens and ACLs",
            ))
            .unwrap();

        let chunk_store = Arc::new(navra_rag::ChunkStore::open_memory(4).unwrap());
        // Two chunks: one about security, one about logging
        let chunks = vec![
            navra_rag::chunk::Chunk {
                content: "BLAKE3 token validation with deny-wins ACLs".to_string(),
                start_byte: 0, end_byte: 44, index: 0, breadcrumb: None,
                section_start_byte: None,
                section_end_byte: None,
            },
            navra_rag::chunk::Chunk {
                content: "Structured JSON logging to stderr".to_string(),
                start_byte: 45, end_byte: 77, index: 1, breadcrumb: None,
                section_start_byte: None,
                section_end_byte: None,
            },
        ];
        let embeddings = vec![
            vec![1.0_f32, 0.0, 0.0, 0.0], // security
            vec![0.0_f32, 1.0, 0.0, 0.0], // logging
        ];
        chunk_store
            .index_document("/module.rs", &chunks, &embeddings)
            .unwrap();

        let retriever = MemoryRetriever::new(&store).with_chunk_store(chunk_store);

        // Query embedding points toward logging
        let query_embedding = vec![0.0_f32, 0.9, 0.1, 0.0];
        // HyDE embedding points toward security (hypothetical answer is about security)
        let hyde_embedding = vec![0.9_f32, 0.0, 0.1, 0.0];

        let results = retriever
            .retrieve_with_hyde("Security", &query_embedding, &hyde_embedding, 10)
            .unwrap();

        let ids: Vec<&str> = results.iter().map(|r| r.entry.id.as_str()).collect();
        // Both vector (logging-similar) and HyDE (security-similar) results should be present
        assert!(
            ids.iter().any(|id| id.starts_with("rag:")),
            "Vector results should be present"
        );
        assert!(
            ids.iter().any(|id| id.starts_with("hyde:")),
            "HyDE results should be present"
        );

        // HyDE result should contain the security chunk (matching the hyde embedding)
        let hyde_entry = results
            .iter()
            .find(|r| r.entry.id.starts_with("hyde:"))
            .expect("HyDE entry should exist");
        assert!(
            hyde_entry.entry.content.contains("BLAKE3"),
            "HyDE channel should find the security chunk via hyde_embedding"
        );

        // Vector result should contain the logging chunk (matching the query embedding)
        let rag_entry = results
            .iter()
            .find(|r| r.entry.id.starts_with("rag:"))
            .expect("Vector entry should exist");
        assert!(
            rag_entry.entry.content.contains("logging"),
            "Vector channel should find the logging chunk via query_embedding"
        );
    }

    #[test]
    fn rrf_respects_top_n() {
        let store = KnowledgeStore::open_memory().unwrap();
        for i in 0..10 {
            store
                .store(&make_entry(
                    &format!("e{i}"),
                    &format!("Topic {i} about testing"),
                    &format!("Content about testing number {i}"),
                ))
                .unwrap();
        }

        let retriever = MemoryRetriever::new(&store);
        let results = retriever.retrieve("testing", 3).unwrap();
        assert!(results.len() <= 3);
    }
}
