//! Causal provenance graphs for multi-agent accountability.
//!
//! Tracks causal relationships across tool calls, agent messages,
//! and flow node outputs using a typed DAG with W3C PROV-DM-aligned
//! edge types. Answers "WHY did this happen?" via BFS traversal.

use rusqlite::Connection;
use std::collections::{HashSet, VecDeque};
use std::path::Path;
use std::sync::Mutex;

/// Types of nodes in the causal graph (W3C PROV-DM aligned).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CausalNodeType {
    /// A tool call execution (PROV: Activity).
    ToolCall {
        tool_name: String,
        agent_id: String,
        session_id: String,
    },
    /// An agent reasoning or action step (PROV: Activity).
    AgentAction {
        agent_id: String,
        action_type: String,
    },
    /// Data written to blackboard (PROV: Entity).
    BlackboardWrite { key: String, version: u64 },
    /// Output of a flow node (PROV: Entity).
    FlowNodeOutput { flow_id: String, task_id: String },
    /// A mailbox message (PROV: Entity).
    Message { sender: String, receiver: String },
}

/// Types of causal edges (W3C PROV-DM aligned).
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CausalEdgeType {
    /// Entity was derived from another entity (prov:wasDerivedFrom).
    WasDerivedFrom,
    /// Entity was generated by an activity (prov:wasGeneratedBy).
    WasGeneratedBy,
    /// Activity used an entity (prov:used).
    Used,
    /// Activity was informed by another (prov:wasInformedBy).
    WasInformedBy,
    /// Activity was triggered by another (navra extension).
    WasTriggeredBy,
}

impl CausalEdgeType {
    fn as_str(&self) -> &'static str {
        match self {
            Self::WasDerivedFrom => "was_derived_from",
            Self::WasGeneratedBy => "was_generated_by",
            Self::Used => "used",
            Self::WasInformedBy => "was_informed_by",
            Self::WasTriggeredBy => "was_triggered_by",
        }
    }

    fn from_str(s: &str) -> Option<Self> {
        match s {
            "was_derived_from" => Some(Self::WasDerivedFrom),
            "was_generated_by" => Some(Self::WasGeneratedBy),
            "used" => Some(Self::Used),
            "was_informed_by" => Some(Self::WasInformedBy),
            "was_triggered_by" => Some(Self::WasTriggeredBy),
            _ => None,
        }
    }
}

/// A node in the causal graph.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CausalNode {
    pub id: String,
    pub node_type: CausalNodeType,
    pub flow_id: Option<String>,
    pub timestamp_ms: i64,
}

/// A directed edge in the causal graph.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CausalEdge {
    pub source_id: String,
    pub target_id: String,
    pub edge_type: CausalEdgeType,
    pub flow_id: Option<String>,
    pub timestamp_ms: i64,
}

/// A subgraph returned by query operations.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct CausalSubgraph {
    pub nodes: Vec<CausalNode>,
    pub edges: Vec<CausalEdge>,
}

impl CausalSubgraph {
    /// Serialize the subgraph to a JSON structure suitable for React Flow
    /// visualization. Nodes include type, label, and placeholder coordinates.
    /// Edges include source, target, edge type, and a human-readable label.
    pub fn to_viz_json(&self) -> serde_json::Value {
        let nodes: Vec<serde_json::Value> = self
            .nodes
            .iter()
            .enumerate()
            .map(|(i, node)| {
                let (node_type, label) = match &node.node_type {
                    CausalNodeType::ToolCall {
                        tool_name,
                        agent_id,
                        ..
                    } => ("activity", format!("{tool_name} ({agent_id})")),
                    CausalNodeType::AgentAction {
                        agent_id,
                        action_type,
                    } => ("activity", format!("{action_type} ({agent_id})")),
                    CausalNodeType::BlackboardWrite { key, version } => {
                        ("entity", format!("{key} v{version}"))
                    }
                    CausalNodeType::FlowNodeOutput { task_id, .. } => {
                        ("entity", format!("output:{task_id}"))
                    }
                    CausalNodeType::Message { sender, receiver } => {
                        ("entity", format!("{sender} -> {receiver}"))
                    }
                };
                serde_json::json!({
                    "id": node.id,
                    "type": node_type,
                    "label": label,
                    "status": "complete",
                    "x": (i % 4) * 250,
                    "y": (i / 4) * 150,
                })
            })
            .collect();

        let edges: Vec<serde_json::Value> = self
            .edges
            .iter()
            .map(|edge| {
                let label = match edge.edge_type {
                    CausalEdgeType::WasDerivedFrom => "derived",
                    CausalEdgeType::WasGeneratedBy => "generated",
                    CausalEdgeType::Used => "used",
                    CausalEdgeType::WasInformedBy => "informed",
                    CausalEdgeType::WasTriggeredBy => "triggered",
                };
                serde_json::json!({
                    "source": edge.source_id,
                    "target": edge.target_id,
                    "type": edge.edge_type.as_str(),
                    "label": label,
                })
            })
            .collect();

        serde_json::json!({
            "nodes": nodes,
            "edges": edges,
        })
    }

    /// Render the subgraph as a Graphviz DOT string.
    pub fn to_dot(&self) -> String {
        let mut out = String::from("digraph causal {\n  rankdir=LR;\n");
        for node in &self.nodes {
            let (shape, label) = match &node.node_type {
                CausalNodeType::ToolCall { tool_name, .. } => ("box", tool_name.clone()),
                CausalNodeType::AgentAction { action_type, .. } => ("box", action_type.clone()),
                CausalNodeType::BlackboardWrite { key, version } => {
                    ("ellipse", format!("{key} v{version}"))
                }
                CausalNodeType::FlowNodeOutput { task_id, .. } => {
                    ("ellipse", format!("output:{task_id}"))
                }
                CausalNodeType::Message { sender, receiver } => {
                    ("note", format!("{sender}->{receiver}"))
                }
            };
            out.push_str(&format!(
                "  \"{}\" [shape={}, label=\"{}\"];\n",
                node.id, shape, label
            ));
        }
        for edge in &self.edges {
            out.push_str(&format!(
                "  \"{}\" -> \"{}\" [label=\"{}\"];\n",
                edge.source_id,
                edge.target_id,
                edge.edge_type.as_str()
            ));
        }
        out.push_str("}\n");
        out
    }
}

/// SQLite-backed causal graph storage.
pub struct CausalGraphStore {
    db: Mutex<Connection>,
}

impl CausalGraphStore {
    /// Open a persistent store at the given path.
    pub fn open(path: &Path) -> anyhow::Result<Self> {
        let conn = Connection::open(path)?;
        let store = Self {
            db: Mutex::new(conn),
        };
        store.init_schema()?;
        Ok(store)
    }

    /// Open an in-memory store (for tests).
    pub fn open_memory() -> anyhow::Result<Self> {
        let conn = Connection::open_in_memory()?;
        let store = Self {
            db: Mutex::new(conn),
        };
        store.init_schema()?;
        Ok(store)
    }

    fn init_schema(&self) -> anyhow::Result<()> {
        let db = self.db.lock().unwrap();
        db.execute_batch(
            "CREATE TABLE IF NOT EXISTS causal_nodes (
                id TEXT PRIMARY KEY,
                node_type TEXT NOT NULL,
                flow_id TEXT,
                timestamp_ms INTEGER NOT NULL
            );
            CREATE TABLE IF NOT EXISTS causal_edges (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source_id TEXT NOT NULL,
                target_id TEXT NOT NULL,
                edge_type TEXT NOT NULL,
                flow_id TEXT,
                timestamp_ms INTEGER NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_edges_source ON causal_edges(source_id);
            CREATE INDEX IF NOT EXISTS idx_edges_target ON causal_edges(target_id);
            CREATE INDEX IF NOT EXISTS idx_nodes_flow ON causal_nodes(flow_id);",
        )?;
        Ok(())
    }

    pub fn insert_node(&self, node: &CausalNode) -> anyhow::Result<()> {
        let db = self.db.lock().unwrap();
        let node_type_json = serde_json::to_string(&node.node_type)?;
        db.execute(
            "INSERT OR REPLACE INTO causal_nodes (id, node_type, flow_id, timestamp_ms)
             VALUES (?1, ?2, ?3, ?4)",
            rusqlite::params![node.id, node_type_json, node.flow_id, node.timestamp_ms],
        )?;
        Ok(())
    }

    pub fn insert_edge(&self, edge: &CausalEdge) -> anyhow::Result<i64> {
        let db = self.db.lock().unwrap();
        db.execute(
            "INSERT INTO causal_edges (source_id, target_id, edge_type, flow_id, timestamp_ms)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            rusqlite::params![
                edge.source_id,
                edge.target_id,
                edge.edge_type.as_str(),
                edge.flow_id,
                edge.timestamp_ms,
            ],
        )?;
        Ok(db.last_insert_rowid())
    }

    /// Trace all causes of a node (BFS backward through target->source).
    pub fn trace_causes(&self, node_id: &str, max_depth: u32) -> anyhow::Result<CausalSubgraph> {
        self.bfs_traverse(node_id, max_depth, Direction::Backward)
    }

    /// Trace all effects of a node (BFS forward through source->target).
    pub fn trace_effects(&self, node_id: &str, max_depth: u32) -> anyhow::Result<CausalSubgraph> {
        self.bfs_traverse(node_id, max_depth, Direction::Forward)
    }

    /// Find root causes: nodes with no incoming edges in the causal subgraph.
    pub fn root_causes(&self, node_id: &str) -> anyhow::Result<Vec<CausalNode>> {
        let subgraph = self.trace_causes(node_id, 100)?;
        let has_incoming: HashSet<&str> = subgraph
            .edges
            .iter()
            .map(|e| e.source_id.as_str())
            .collect();
        Ok(subgraph
            .nodes
            .into_iter()
            .filter(|n| !has_incoming.contains(n.id.as_str()))
            .collect())
    }

    /// Get all nodes and edges for a flow.
    pub fn flow_graph(&self, flow_id: &str) -> anyhow::Result<CausalSubgraph> {
        let db = self.db.lock().unwrap();
        let mut nodes = Vec::new();
        {
            let mut stmt = db.prepare(
                "SELECT id, node_type, flow_id, timestamp_ms FROM causal_nodes WHERE flow_id = ?1",
            )?;
            let rows = stmt.query_map([flow_id], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, Option<String>>(2)?,
                    row.get::<_, i64>(3)?,
                ))
            })?;
            for row in rows {
                let (id, node_type_json, fid, ts) = row?;
                let node_type: CausalNodeType = serde_json::from_str(&node_type_json)?;
                nodes.push(CausalNode {
                    id,
                    node_type,
                    flow_id: fid,
                    timestamp_ms: ts,
                });
            }
        }
        let mut edges = Vec::new();
        {
            let mut stmt = db.prepare(
                "SELECT source_id, target_id, edge_type, flow_id, timestamp_ms
                 FROM causal_edges WHERE flow_id = ?1",
            )?;
            let rows = stmt.query_map([flow_id], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, String>(2)?,
                    row.get::<_, Option<String>>(3)?,
                    row.get::<_, i64>(4)?,
                ))
            })?;
            for row in rows {
                let (src, tgt, et, fid, ts) = row?;
                if let Some(edge_type) = CausalEdgeType::from_str(&et) {
                    edges.push(CausalEdge {
                        source_id: src,
                        target_id: tgt,
                        edge_type,
                        flow_id: fid,
                        timestamp_ms: ts,
                    });
                }
            }
        }
        Ok(CausalSubgraph { nodes, edges })
    }

    fn bfs_traverse(
        &self,
        start_id: &str,
        max_depth: u32,
        direction: Direction,
    ) -> anyhow::Result<CausalSubgraph> {
        let db = self.db.lock().unwrap();

        let mut visited: HashSet<String> = HashSet::new();
        let mut queue: VecDeque<(String, u32)> = VecDeque::new();
        let mut result_nodes = Vec::new();
        let mut result_edges = Vec::new();

        // Load start node if it exists
        if let Some(node) = Self::load_node(&db, start_id)? {
            result_nodes.push(node);
            visited.insert(start_id.to_string());
            queue.push_back((start_id.to_string(), 0));
        }

        let edge_col = match direction {
            Direction::Backward => "source_id",
            Direction::Forward => "target_id",
        };

        while let Some((current_id, depth)) = queue.pop_front() {
            if depth >= max_depth {
                continue;
            }
            let query = format!(
                "SELECT source_id, target_id, edge_type, flow_id, timestamp_ms
                 FROM causal_edges WHERE {edge_col} = ?1"
            );
            let mut stmt = db.prepare(&query)?;
            let rows = stmt.query_map([&current_id], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, String>(2)?,
                    row.get::<_, Option<String>>(3)?,
                    row.get::<_, i64>(4)?,
                ))
            })?;
            for row in rows {
                let (src, tgt, et, fid, ts) = row?;
                if let Some(edge_type) = CausalEdgeType::from_str(&et) {
                    result_edges.push(CausalEdge {
                        source_id: src.clone(),
                        target_id: tgt.clone(),
                        edge_type,
                        flow_id: fid,
                        timestamp_ms: ts,
                    });
                    let neighbor = match direction {
                        Direction::Backward => &tgt,
                        Direction::Forward => &src,
                    };
                    if !visited.contains(neighbor) {
                        visited.insert(neighbor.clone());
                        if let Some(node) = Self::load_node(&db, neighbor)? {
                            result_nodes.push(node);
                        }
                        queue.push_back((neighbor.clone(), depth + 1));
                    }
                }
            }
        }

        Ok(CausalSubgraph {
            nodes: result_nodes,
            edges: result_edges,
        })
    }

    fn load_node(db: &Connection, id: &str) -> anyhow::Result<Option<CausalNode>> {
        let mut stmt = db.prepare(
            "SELECT id, node_type, flow_id, timestamp_ms FROM causal_nodes WHERE id = ?1",
        )?;
        let mut rows = stmt.query_map([id], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, Option<String>>(2)?,
                row.get::<_, i64>(3)?,
            ))
        })?;
        if let Some(row) = rows.next() {
            let (id, node_type_json, flow_id, timestamp_ms) = row?;
            let node_type: CausalNodeType = serde_json::from_str(&node_type_json)?;
            Ok(Some(CausalNode {
                id,
                node_type,
                flow_id,
                timestamp_ms,
            }))
        } else {
            Ok(None)
        }
    }
}

enum Direction {
    Backward,
    Forward,
}

impl navra_safety_hooks::hooks::CausalSink for CausalGraphStore {
    fn record_tool_call(
        &self,
        node_id: &str,
        tool_name: &str,
        agent_id: &str,
        session_id: &str,
        _input_node_ids: &[String],
    ) {
        let now_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64;

        let node = CausalNode {
            id: node_id.to_string(),
            node_type: CausalNodeType::ToolCall {
                tool_name: tool_name.to_string(),
                agent_id: agent_id.to_string(),
                session_id: session_id.to_string(),
            },
            flow_id: None,
            timestamp_ms: now_ms,
        };
        if let Err(e) = self.insert_node(&node) {
            tracing::warn!(error = %e, "Failed to record causal tool-call node");
        }
    }

    fn record_tool_result(&self, result_node_id: &str, tool_call_node_id: &str) {
        let now_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as i64;

        let node = CausalNode {
            id: result_node_id.to_string(),
            node_type: CausalNodeType::AgentAction {
                agent_id: String::new(),
                action_type: "tool_result".to_string(),
            },
            flow_id: None,
            timestamp_ms: now_ms,
        };
        if let Err(e) = self.insert_node(&node) {
            tracing::warn!(error = %e, "Failed to record causal result node");
        }

        let edge = CausalEdge {
            source_id: result_node_id.to_string(),
            target_id: tool_call_node_id.to_string(),
            edge_type: CausalEdgeType::WasGeneratedBy,
            flow_id: None,
            timestamp_ms: now_ms,
        };
        if let Err(e) = self.insert_edge(&edge) {
            tracing::warn!(error = %e, "Failed to record causal edge");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn insert_and_retrieve_node() {
        let store = CausalGraphStore::open_memory().unwrap();
        let node = CausalNode {
            id: "node-1".to_string(),
            node_type: CausalNodeType::ToolCall {
                tool_name: "file_read".to_string(),
                agent_id: "agent-a".to_string(),
                session_id: "sess-1".to_string(),
            },
            flow_id: Some("flow-1".to_string()),
            timestamp_ms: 1000,
        };
        store.insert_node(&node).unwrap();
        let graph = store.flow_graph("flow-1").unwrap();
        assert_eq!(graph.nodes.len(), 1);
        assert_eq!(graph.nodes[0].id, "node-1");
    }

    #[test]
    fn insert_edge_and_trace_causes() {
        let store = CausalGraphStore::open_memory().unwrap();
        // A -> B -> C (B was derived from A, C was derived from B)
        for (id, ts) in [("a", 1), ("b", 2), ("c", 3)] {
            store
                .insert_node(&CausalNode {
                    id: id.to_string(),
                    node_type: CausalNodeType::FlowNodeOutput {
                        flow_id: "f1".to_string(),
                        task_id: id.to_string(),
                    },
                    flow_id: Some("f1".to_string()),
                    timestamp_ms: ts,
                })
                .unwrap();
        }
        store
            .insert_edge(&CausalEdge {
                source_id: "b".to_string(),
                target_id: "a".to_string(),
                edge_type: CausalEdgeType::WasDerivedFrom,
                flow_id: Some("f1".to_string()),
                timestamp_ms: 2,
            })
            .unwrap();
        store
            .insert_edge(&CausalEdge {
                source_id: "c".to_string(),
                target_id: "b".to_string(),
                edge_type: CausalEdgeType::WasDerivedFrom,
                flow_id: Some("f1".to_string()),
                timestamp_ms: 3,
            })
            .unwrap();

        let subgraph = store.trace_causes("c", 10).unwrap();
        assert_eq!(subgraph.nodes.len(), 3);
        assert_eq!(subgraph.edges.len(), 2);
    }

    #[test]
    fn trace_causes_respects_max_depth() {
        let store = CausalGraphStore::open_memory().unwrap();
        for i in 0..5 {
            store
                .insert_node(&CausalNode {
                    id: format!("n{i}"),
                    node_type: CausalNodeType::FlowNodeOutput {
                        flow_id: "f1".to_string(),
                        task_id: format!("t{i}"),
                    },
                    flow_id: Some("f1".to_string()),
                    timestamp_ms: i as i64,
                })
                .unwrap();
        }
        for i in 1..5 {
            store
                .insert_edge(&CausalEdge {
                    source_id: format!("n{i}"),
                    target_id: format!("n{}", i - 1),
                    edge_type: CausalEdgeType::WasDerivedFrom,
                    flow_id: Some("f1".to_string()),
                    timestamp_ms: i as i64,
                })
                .unwrap();
        }
        let subgraph = store.trace_causes("n4", 2).unwrap();
        // depth 2: n4 -> n3 -> n2 (3 nodes, 2 edges)
        assert_eq!(subgraph.nodes.len(), 3);
    }

    #[test]
    fn root_causes_finds_sources() {
        let store = CausalGraphStore::open_memory().unwrap();
        for id in ["root1", "root2", "mid", "leaf"] {
            store
                .insert_node(&CausalNode {
                    id: id.to_string(),
                    node_type: CausalNodeType::ToolCall {
                        tool_name: "t".to_string(),
                        agent_id: "a".to_string(),
                        session_id: "s".to_string(),
                    },
                    flow_id: None,
                    timestamp_ms: 0,
                })
                .unwrap();
        }
        store
            .insert_edge(&CausalEdge {
                source_id: "mid".to_string(),
                target_id: "root1".to_string(),
                edge_type: CausalEdgeType::Used,
                flow_id: None,
                timestamp_ms: 0,
            })
            .unwrap();
        store
            .insert_edge(&CausalEdge {
                source_id: "mid".to_string(),
                target_id: "root2".to_string(),
                edge_type: CausalEdgeType::Used,
                flow_id: None,
                timestamp_ms: 0,
            })
            .unwrap();
        store
            .insert_edge(&CausalEdge {
                source_id: "leaf".to_string(),
                target_id: "mid".to_string(),
                edge_type: CausalEdgeType::WasDerivedFrom,
                flow_id: None,
                timestamp_ms: 0,
            })
            .unwrap();

        let roots = store.root_causes("leaf").unwrap();
        let mut root_ids: Vec<_> = roots.iter().map(|n| n.id.as_str()).collect();
        root_ids.sort();
        assert_eq!(root_ids, vec!["root1", "root2"]);
    }

    #[test]
    fn trace_effects_forward() {
        let store = CausalGraphStore::open_memory().unwrap();
        for id in ["src", "mid", "dst"] {
            store
                .insert_node(&CausalNode {
                    id: id.to_string(),
                    node_type: CausalNodeType::ToolCall {
                        tool_name: "t".to_string(),
                        agent_id: "a".to_string(),
                        session_id: "s".to_string(),
                    },
                    flow_id: None,
                    timestamp_ms: 0,
                })
                .unwrap();
        }
        store
            .insert_edge(&CausalEdge {
                source_id: "mid".to_string(),
                target_id: "src".to_string(),
                edge_type: CausalEdgeType::WasDerivedFrom,
                flow_id: None,
                timestamp_ms: 0,
            })
            .unwrap();
        store
            .insert_edge(&CausalEdge {
                source_id: "dst".to_string(),
                target_id: "mid".to_string(),
                edge_type: CausalEdgeType::WasDerivedFrom,
                flow_id: None,
                timestamp_ms: 0,
            })
            .unwrap();

        let subgraph = store.trace_effects("src", 10).unwrap();
        assert_eq!(subgraph.nodes.len(), 3);
    }

    #[test]
    fn empty_graph_returns_empty_subgraph() {
        let store = CausalGraphStore::open_memory().unwrap();
        let subgraph = store.trace_causes("nonexistent", 10).unwrap();
        assert!(subgraph.nodes.is_empty());
        assert!(subgraph.edges.is_empty());
    }

    #[test]
    fn causal_sink_records_tool_call_and_result() {
        use navra_safety_hooks::hooks::CausalSink;
        let store = CausalGraphStore::open_memory().unwrap();
        store.record_tool_call("tc-1", "file_read", "agent-a", "sess-1", &[]);
        store.record_tool_result("tr-1", "tc-1");

        let graph = store.trace_effects("tc-1", 10).unwrap();
        assert_eq!(graph.nodes.len(), 2);
        assert_eq!(graph.edges.len(), 1);
        assert_eq!(graph.edges[0].edge_type, CausalEdgeType::WasGeneratedBy);
    }

    #[test]
    fn to_viz_json_simple_graph() {
        let subgraph = CausalSubgraph {
            nodes: vec![
                CausalNode {
                    id: "n1".to_string(),
                    node_type: CausalNodeType::ToolCall {
                        tool_name: "file_read".to_string(),
                        agent_id: "agent-a".to_string(),
                        session_id: "s1".to_string(),
                    },
                    flow_id: Some("f1".to_string()),
                    timestamp_ms: 100,
                },
                CausalNode {
                    id: "n2".to_string(),
                    node_type: CausalNodeType::FlowNodeOutput {
                        flow_id: "f1".to_string(),
                        task_id: "task-1".to_string(),
                    },
                    flow_id: Some("f1".to_string()),
                    timestamp_ms: 200,
                },
            ],
            edges: vec![CausalEdge {
                source_id: "n2".to_string(),
                target_id: "n1".to_string(),
                edge_type: CausalEdgeType::WasGeneratedBy,
                flow_id: Some("f1".to_string()),
                timestamp_ms: 200,
            }],
        };

        let json = subgraph.to_viz_json();

        let nodes = json["nodes"].as_array().unwrap();
        assert_eq!(nodes.len(), 2);
        assert_eq!(nodes[0]["id"], "n1");
        assert_eq!(nodes[0]["type"], "activity");
        assert!(nodes[0]["label"].as_str().unwrap().contains("file_read"));
        assert_eq!(nodes[1]["id"], "n2");
        assert_eq!(nodes[1]["type"], "entity");

        let edges = json["edges"].as_array().unwrap();
        assert_eq!(edges.len(), 1);
        assert_eq!(edges[0]["source"], "n2");
        assert_eq!(edges[0]["target"], "n1");
        assert_eq!(edges[0]["type"], "was_generated_by");
        assert_eq!(edges[0]["label"], "generated");
    }

    #[test]
    fn to_viz_json_empty_graph() {
        let subgraph = CausalSubgraph::default();
        let json = subgraph.to_viz_json();
        assert_eq!(json["nodes"].as_array().unwrap().len(), 0);
        assert_eq!(json["edges"].as_array().unwrap().len(), 0);
    }

    #[test]
    fn to_dot_format() {
        let subgraph = CausalSubgraph {
            nodes: vec![
                CausalNode {
                    id: "a".to_string(),
                    node_type: CausalNodeType::ToolCall {
                        tool_name: "file_read".to_string(),
                        agent_id: "agent-a".to_string(),
                        session_id: "s1".to_string(),
                    },
                    flow_id: None,
                    timestamp_ms: 0,
                },
                CausalNode {
                    id: "b".to_string(),
                    node_type: CausalNodeType::BlackboardWrite {
                        key: "findings".to_string(),
                        version: 1,
                    },
                    flow_id: None,
                    timestamp_ms: 0,
                },
            ],
            edges: vec![CausalEdge {
                source_id: "b".to_string(),
                target_id: "a".to_string(),
                edge_type: CausalEdgeType::Used,
                flow_id: None,
                timestamp_ms: 0,
            }],
        };

        let dot = subgraph.to_dot();
        assert!(dot.starts_with("digraph causal {"));
        assert!(dot.contains("rankdir=LR"));
        assert!(dot.contains("\"a\""));
        assert!(dot.contains("shape=box"));
        assert!(dot.contains("\"b\""));
        assert!(dot.contains("shape=ellipse"));
        assert!(dot.contains("\"b\" -> \"a\""));
        assert!(dot.contains("label=\"used\""));
        assert!(dot.ends_with("}\n"));
    }

    #[test]
    fn to_dot_empty_graph() {
        let subgraph = CausalSubgraph::default();
        let dot = subgraph.to_dot();
        assert!(dot.starts_with("digraph causal {"));
        assert!(dot.ends_with("}\n"));
    }
}

#[cfg(kani)]
mod kani_proofs {
    use super::*;

    fn arbitrary_edge_type() -> CausalEdgeType {
        match kani::any::<u8>() % 5 {
            0 => CausalEdgeType::WasDerivedFrom,
            1 => CausalEdgeType::WasGeneratedBy,
            2 => CausalEdgeType::Used,
            3 => CausalEdgeType::WasInformedBy,
            _ => CausalEdgeType::WasTriggeredBy,
        }
    }

    #[kani::proof]
    fn edge_type_roundtrip() {
        let t = arbitrary_edge_type();
        assert_eq!(CausalEdgeType::from_str(t.as_str()), Some(t));
    }
}
