use serde::Serialize;
use std::fmt;

/// Summary of detected hardware resources.
#[derive(Debug, Clone, Serialize)]
pub struct HardwareSummary {
    pub gpus: Vec<GpuInfo>,
    pub npus: Vec<NpuInfo>,
    pub system_ram_bytes: u64,
    pub suggested_vram_budget: u64,
    pub desktop_reservation: u64,
}

#[derive(Debug, Clone, Serialize)]
pub struct GpuInfo {
    pub kind: String,
    pub index: u32,
    pub name: String,
    pub vram_bytes: Option<u64>,
    pub vram_used_bytes: Option<u64>,
}

#[derive(Debug, Clone, Serialize)]
pub struct NpuInfo {
    pub name: String,
    pub device_path: String,
}

/// Hardware profile for config generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum HardwareProfile {
    /// Discrete GPU with ≥16GB VRAM (NVIDIA or AMD).
    Desktop,
    /// Intel NPU detected, no discrete GPU (or iGPU only).
    Laptop,
    /// CPU only — no GPU, no NPU.
    Headless,
}

impl HardwareProfile {
    /// Minimum VRAM (bytes) to classify a GPU as "desktop-class".
    const DESKTOP_VRAM_THRESHOLD: u64 = 16 * 1024 * 1024 * 1024;
}

impl fmt::Display for HardwareProfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Desktop => f.write_str("desktop"),
            Self::Laptop => f.write_str("laptop"),
            Self::Headless => f.write_str("headless"),
        }
    }
}

impl std::str::FromStr for HardwareProfile {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "desktop" => Ok(Self::Desktop),
            "laptop" => Ok(Self::Laptop),
            "headless" => Ok(Self::Headless),
            other => Err(format!(
                "unknown profile: {other} (expected desktop, laptop, or headless)"
            )),
        }
    }
}

/// Classify detected hardware into a profile.
pub fn classify(summary: &HardwareSummary) -> HardwareProfile {
    let has_discrete_gpu = summary.gpus.iter().any(|g| {
        let is_discrete = g.kind == "nvidia" || g.kind == "amd";
        let has_enough_vram = g
            .vram_bytes
            .map(|v| v >= HardwareProfile::DESKTOP_VRAM_THRESHOLD)
            .unwrap_or(false);
        is_discrete && has_enough_vram
    });

    if has_discrete_gpu {
        HardwareProfile::Desktop
    } else if !summary.npus.is_empty() {
        HardwareProfile::Laptop
    } else {
        HardwareProfile::Headless
    }
}

/// Generate a complete config.toml tuned to the hardware profile.
pub fn generate_config(profile: &HardwareProfile) -> String {
    match profile {
        HardwareProfile::Desktop => DESKTOP_CONFIG.to_string(),
        HardwareProfile::Laptop => LAPTOP_CONFIG.to_string(),
        HardwareProfile::Headless => HEADLESS_CONFIG.to_string(),
    }
}

const LAPTOP_CONFIG: &str = r##"# navra configuration — laptop profile (Intel Core Ultra / NPU)
#
# Generated by: navra init --profile laptop
# Hardware: Intel Core Ultra with NPU + iGPU, no discrete GPU.
#
# Routing: NPU for classifiers/embeddings (fastest, lowest power),
# CPU for tiny models (<5MB), iGPU for autoregressive reasoning.

[server]
socket = "~/.run/navra/navra.sock"
mcp_version = "2026-07-28"

# ── Modules ────────────────────────────────────────────────────

[modules.file]
enabled = true
db = "~/.local/share/navra/index.db"

[modules.git]
enabled = true

[modules.github]
enabled = true

[modules.rag]
enabled = true
db = "~/.local/share/navra/rag.db"
query_cache_ttl_secs = 300

[modules.voice]
enabled = false
# asr_model = "asr"       # Whisper on NPU via OpenVINO GenAI
# tts_model = "tts"       # Kokoro on NPU

[modules.memory]
pii_filter = "standard"

# ── Models ─────────────────────────────────────────────────────
# In-process ONNX models routed to NPU via OpenVINO AUTO EP.
# OpenVINO AUTO selects: NPU > iGPU > CPU automatically.

[models.safety]
model_path = "~/.local/share/navra/models/granite-guardian-hap-38m-int8.onnx"
tokenizer_path = "~/.local/share/navra/models/granite-guardian-hap-38m/tokenizer.json"
task = "classification"
labels = ["safe", "unsafe"]
threshold = 0.5
device = "openvino:AUTO"

[models.embeddings]
model_path = "~/.local/share/navra/models/granite-embedding-r2-int8.onnx"
tokenizer_path = "~/.local/share/navra/models/granite-embedding-r2/tokenizer.json"
task = "embedding"
dimensions = 768
device = "openvino:AUTO"

[models.vad]
model_path = "~/.local/share/navra/models/silero-vad.onnx"
task = "classification"
labels = ["silence", "speech"]
device = "cpu"

# [models.tts]
# model_path = "~/.local/share/navra/models/kokoro-82m-fp16.onnx"
# task = "generate"
# execution_mode = "in_process"
# device = "openvino:AUTO"

# [models.asr]
# model_path = "~/.local/share/navra/models/ggml-large-v3-turbo.bin"
# task = "generate"
# execution_mode = "in_process"

# ── iGPU reasoning (optional, requires Ollama with SYCL) ──────
# Gemma 4 E4B on Intel Arc iGPU. Enable after installing Ollama
# with SYCL support: ollama pull gemma4:e4b
#
# [models.reasoning]
# source = "ollama://gemma4:e4b"
# task = "chat"
# runtime = "ollama"
# locality = "local"
# context_size = 4096
# kv_cache = { keys = "q8_0", values = "turbo3" }

# ── Agents ─────────────────────────────────────────────────────

[[agents]]
name = "claude"
token_hash = "REPLACE_WITH_HASH_FROM_TOKEN_GENERATE"
permissions = "dev"

# ── Permissions ────────────────────────────────────────────────

[permissions.dev]
ring = 1
allow = ["file_*", "git_*", "github_*", "rag_*", "memory_*"]
deny = ["exec_run"]
safety = "standard"
default_tool_policy = "allow"
can_delegate = true

[[permissions.dev.tool_rules]]
tool = "exec_*"
policy = "approve"

[[permissions.dev.tool_rules]]
tool = "git_push"
policy = "approve"

[permissions.readonly]
ring = 2
allow = ["file_read", "file_list", "file_tree", "git_status", "git_log", "git_diff", "rag_*"]
deny = ["file_write", "file_delete", "git_commit", "git_push", "exec_*"]
safety = "standard"

# ── Budget ─────────────────────────────────────────────────────
# Conservative for laptop: lower parallelism, shorter timeout.

[budget]
max_agents = 20
max_iterations = 100
max_parallel = 1
timeout_secs = 1800

[approval]
timeout_secs = 300
notify = "dbus"
"##;

const DESKTOP_CONFIG: &str = r##"# navra configuration — desktop profile (discrete GPU)
#
# Generated by: navra init --profile desktop
# Hardware: discrete NVIDIA/AMD GPU with ≥16GB VRAM.

[server]
socket = "~/.run/navra/navra.sock"
mcp_version = "2026-07-28"

# ── Modules ────────────────────────────────────────────────────

[modules.file]
enabled = true
db = "~/.local/share/navra/index.db"

[modules.git]
enabled = true

[modules.github]
enabled = true

[modules.rag]
enabled = true
db = "~/.local/share/navra/rag.db"
query_cache_ttl_secs = 300

[modules.voice]
enabled = false
# asr_model = "asr"
# tts_model = "tts"

[modules.memory]
pii_filter = "standard"

# ── Models ─────────────────────────────────────────────────────
# CPU tier: in-process ONNX (too small to benefit from GPU).
# GPU tier: served via runtime (vLLM or llama.cpp).

[models.safety]
model_path = "~/.local/share/navra/models/granite-guardian-hap-38m-int8.onnx"
tokenizer_path = "~/.local/share/navra/models/granite-guardian-hap-38m/tokenizer.json"
task = "classification"
labels = ["safe", "unsafe"]
threshold = 0.5

[models.embeddings]
model_path = "~/.local/share/navra/models/granite-embedding-r2-int8.onnx"
tokenizer_path = "~/.local/share/navra/models/granite-embedding-r2/tokenizer.json"
task = "embedding"
dimensions = 768

[models.vad]
model_path = "~/.local/share/navra/models/silero-vad.onnx"
task = "classification"
labels = ["silence", "speech"]

# GPU reasoning model (enable after pulling the model)
# [models.reasoning]
# source = "ollama://gemma4:26b-a4b"
# task = "chat"
# runtime = "ollama"
# locality = "local"
# context_size = 8192
# kv_cache = { keys = "q8_0", values = "turbo3" }

# ── Agents ─────────────────────────────────────────────────────

[[agents]]
name = "claude"
token_hash = "REPLACE_WITH_HASH_FROM_TOKEN_GENERATE"
permissions = "dev"

# ── Permissions ────────────────────────────────────────────────

[permissions.dev]
ring = 1
allow = ["file_*", "git_*", "github_*", "rag_*", "memory_*"]
deny = ["exec_run"]
safety = "standard"
default_tool_policy = "allow"
can_delegate = true

[[permissions.dev.tool_rules]]
tool = "exec_*"
policy = "approve"

[[permissions.dev.tool_rules]]
tool = "git_push"
policy = "approve"

[permissions.readonly]
ring = 2
allow = ["file_read", "file_list", "file_tree", "git_status", "git_log", "git_diff", "rag_*"]
deny = ["file_write", "file_delete", "git_commit", "git_push", "exec_*"]
safety = "standard"

# ── Budget ─────────────────────────────────────────────────────

[budget]
max_agents = 50
max_iterations = 200
max_parallel = 4
timeout_secs = 3600

[approval]
timeout_secs = 300
notify = "dbus"
"##;

const HEADLESS_CONFIG: &str = r##"# navra configuration — headless profile (CPU only)
#
# Generated by: navra init --profile headless
# Hardware: no GPU, no NPU. Pure CPU inference.

[server]
socket = "~/.run/navra/navra.sock"
mcp_version = "2026-07-28"

# ── Modules ────────────────────────────────────────────────────

[modules.file]
enabled = true
db = "~/.local/share/navra/index.db"

[modules.git]
enabled = true

[modules.github]
enabled = false

[modules.rag]
enabled = true
db = "~/.local/share/navra/rag.db"
query_cache_ttl_secs = 300

[modules.memory]
pii_filter = "standard"

# ── Models ─────────────────────────────────────────────────────
# CPU-only: safety, embeddings, VAD. No reasoning model.

[models.safety]
model_path = "~/.local/share/navra/models/granite-guardian-hap-38m-int8.onnx"
tokenizer_path = "~/.local/share/navra/models/granite-guardian-hap-38m/tokenizer.json"
task = "classification"
labels = ["safe", "unsafe"]
threshold = 0.5

[models.embeddings]
model_path = "~/.local/share/navra/models/granite-embedding-r2-int8.onnx"
tokenizer_path = "~/.local/share/navra/models/granite-embedding-r2/tokenizer.json"
task = "embedding"
dimensions = 768

[models.vad]
model_path = "~/.local/share/navra/models/silero-vad.onnx"
task = "classification"
labels = ["silence", "speech"]

# ── Agents ─────────────────────────────────────────────────────

[[agents]]
name = "claude"
token_hash = "REPLACE_WITH_HASH_FROM_TOKEN_GENERATE"
permissions = "dev"

# ── Permissions ────────────────────────────────────────────────

[permissions.dev]
ring = 1
allow = ["file_*", "git_*", "rag_*", "memory_*"]
deny = ["exec_run"]
safety = "standard"
default_tool_policy = "allow"

[[permissions.dev.tool_rules]]
tool = "exec_*"
policy = "approve"

[permissions.readonly]
ring = 2
allow = ["file_read", "file_list", "file_tree", "git_status", "git_log", "git_diff", "rag_*"]
deny = ["file_write", "file_delete", "git_commit", "git_push", "exec_*"]
safety = "standard"

# ── Budget ─────────────────────────────────────────────────────
# Conservative for CPU-only: no parallelism.

[budget]
max_agents = 10
max_iterations = 50
max_parallel = 1
timeout_secs = 1800

[approval]
timeout_secs = 300
notify = "dbus"
"##;

/// Detect available hardware and propose resource allocation.
pub fn detect(desktop_reservation: u64) -> HardwareSummary {
    let raw_gpus = navra_model_runtime::detect_gpus();
    let raw_npus = navra_model_runtime::detect_npus();

    let gpus: Vec<GpuInfo> = raw_gpus
        .iter()
        .map(|g| {
            let (vram, used) = match g.kind {
                navra_model_runtime::GpuKind::Nvidia => {
                    let mem = navra_model_runtime::gpu::sample_nvidia_memory();
                    mem.iter()
                        .find(|m| m.index == g.index)
                        .map(|m| (Some(m.total), Some(m.used)))
                        .unwrap_or((None, None))
                }
                _ => (g.vram, None),
            };
            GpuInfo {
                kind: format!("{:?}", g.kind).to_lowercase(),
                index: g.index,
                name: g.name.clone(),
                vram_bytes: vram,
                vram_used_bytes: used,
            }
        })
        .collect();

    let npus: Vec<NpuInfo> = raw_npus
        .iter()
        .map(|n| NpuInfo {
            name: format!("Intel NPU ({})", n.pci_id),
            device_path: n.dev_path.clone(),
        })
        .collect();

    let total_vram: u64 = gpus.iter().filter_map(|g| g.vram_bytes).sum();
    let suggested = total_vram.saturating_sub(desktop_reservation);

    let system_ram = sys_ram_bytes();

    HardwareSummary {
        gpus,
        npus,
        system_ram_bytes: system_ram,
        suggested_vram_budget: suggested,
        desktop_reservation,
    }
}

fn sys_ram_bytes() -> u64 {
    std::fs::read_to_string("/proc/meminfo")
        .ok()
        .and_then(|s| {
            s.lines()
                .find(|l| l.starts_with("MemTotal:"))
                .and_then(|l| {
                    l.split_whitespace()
                        .nth(1)
                        .and_then(|v| v.parse::<u64>().ok())
                })
        })
        .map(|kb| kb * 1024)
        .unwrap_or(0)
}

/// Print a human-readable hardware summary to stdout.
pub fn print_summary(summary: &HardwareSummary) {
    println!("Detected resources:");
    if summary.gpus.is_empty() {
        println!("  GPU: none detected");
    } else {
        for gpu in &summary.gpus {
            let vram = gpu
                .vram_bytes
                .map(|v| format!("{}GB VRAM", v / (1024 * 1024 * 1024)))
                .unwrap_or_else(|| "unknown VRAM".to_string());
            println!("  GPU: {} ({}) [{}]", gpu.name, vram, gpu.kind);
        }
    }
    if !summary.npus.is_empty() {
        for npu in &summary.npus {
            println!("  NPU: {} ({})", npu.name, npu.device_path);
        }
    }
    let ram_gb = summary.system_ram_bytes / (1024 * 1024 * 1024);
    println!("  RAM: {}GB", ram_gb);
    println!();

    if summary.suggested_vram_budget > 0 {
        let budget_gb = summary.suggested_vram_budget / (1024 * 1024 * 1024);
        let reserved_gb = summary.desktop_reservation / (1024 * 1024 * 1024);
        println!("Proposed allocation:");
        println!(
            "  GPU: {}GB for models ({}GB reserved for desktop)",
            budget_gb, reserved_gb
        );
    } else {
        println!("Proposed allocation:");
        println!("  CPU-only mode (no GPU detected or budget exhausted)");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const GB: u64 = 1024 * 1024 * 1024;

    #[test]
    fn detect_returns_summary() {
        let summary = detect(2 * GB);
        assert!(summary.system_ram_bytes > 0 || cfg!(not(target_os = "linux")));
    }

    #[test]
    fn print_summary_no_panic() {
        let summary = HardwareSummary {
            gpus: vec![],
            npus: vec![],
            system_ram_bytes: 64 * GB,
            suggested_vram_budget: 0,
            desktop_reservation: 2 * GB,
        };
        print_summary(&summary);
    }

    fn summary_with(gpus: Vec<GpuInfo>, npus: Vec<NpuInfo>) -> HardwareSummary {
        HardwareSummary {
            gpus,
            npus,
            system_ram_bytes: 32 * GB,
            suggested_vram_budget: 0,
            desktop_reservation: 2 * GB,
        }
    }

    #[test]
    fn classify_desktop_nvidia() {
        let summary = summary_with(
            vec![GpuInfo {
                kind: "nvidia".into(),
                index: 0,
                name: "RTX 5090".into(),
                vram_bytes: Some(32 * GB),
                vram_used_bytes: None,
            }],
            vec![],
        );
        assert_eq!(classify(&summary), HardwareProfile::Desktop);
    }

    #[test]
    fn classify_desktop_amd() {
        let summary = summary_with(
            vec![GpuInfo {
                kind: "amd".into(),
                index: 0,
                name: "RX 7900 XTX".into(),
                vram_bytes: Some(24 * GB),
                vram_used_bytes: None,
            }],
            vec![],
        );
        assert_eq!(classify(&summary), HardwareProfile::Desktop);
    }

    #[test]
    fn classify_laptop_npu() {
        let summary = summary_with(
            vec![],
            vec![NpuInfo {
                name: "Intel NPU (8086:643E)".into(),
                device_path: "/dev/accel/accel0".into(),
            }],
        );
        assert_eq!(classify(&summary), HardwareProfile::Laptop);
    }

    #[test]
    fn classify_laptop_npu_with_igpu() {
        let summary = summary_with(
            vec![GpuInfo {
                kind: "intel".into(),
                index: 0,
                name: "Arc 140V".into(),
                vram_bytes: Some(16 * GB),
                vram_used_bytes: None,
            }],
            vec![NpuInfo {
                name: "Intel NPU".into(),
                device_path: "/dev/accel/accel0".into(),
            }],
        );
        assert_eq!(classify(&summary), HardwareProfile::Laptop);
    }

    #[test]
    fn classify_headless() {
        let summary = summary_with(vec![], vec![]);
        assert_eq!(classify(&summary), HardwareProfile::Headless);
    }

    #[test]
    fn classify_small_gpu_as_headless() {
        let summary = summary_with(
            vec![GpuInfo {
                kind: "nvidia".into(),
                index: 0,
                name: "GTX 1650".into(),
                vram_bytes: Some(4 * GB),
                vram_used_bytes: None,
            }],
            vec![],
        );
        assert_eq!(classify(&summary), HardwareProfile::Headless);
    }

    #[test]
    fn desktop_prefers_over_npu() {
        let summary = summary_with(
            vec![GpuInfo {
                kind: "nvidia".into(),
                index: 0,
                name: "RTX 4090".into(),
                vram_bytes: Some(24 * GB),
                vram_used_bytes: None,
            }],
            vec![NpuInfo {
                name: "Intel NPU".into(),
                device_path: "/dev/accel/accel0".into(),
            }],
        );
        assert_eq!(classify(&summary), HardwareProfile::Desktop);
    }

    #[test]
    fn profile_display() {
        assert_eq!(HardwareProfile::Desktop.to_string(), "desktop");
        assert_eq!(HardwareProfile::Laptop.to_string(), "laptop");
        assert_eq!(HardwareProfile::Headless.to_string(), "headless");
    }

    #[test]
    fn profile_from_str() {
        assert_eq!(
            "desktop".parse::<HardwareProfile>().unwrap(),
            HardwareProfile::Desktop
        );
        assert_eq!(
            "laptop".parse::<HardwareProfile>().unwrap(),
            HardwareProfile::Laptop
        );
        assert_eq!(
            "headless".parse::<HardwareProfile>().unwrap(),
            HardwareProfile::Headless
        );
        assert!("invalid".parse::<HardwareProfile>().is_err());
    }

    #[test]
    fn generate_config_laptop_contains_openvino() {
        let cfg = generate_config(&HardwareProfile::Laptop);
        assert!(cfg.contains("openvino:AUTO"));
        assert!(cfg.contains("max_parallel = 1"));
        assert!(cfg.contains("turbo3"));
    }

    #[test]
    fn generate_config_desktop_has_higher_parallelism() {
        let cfg = generate_config(&HardwareProfile::Desktop);
        assert!(cfg.contains("max_parallel = 4"));
        assert!(cfg.contains("turbo3"));
    }

    #[test]
    fn generate_config_headless_cpu_only() {
        let cfg = generate_config(&HardwareProfile::Headless);
        assert!(!cfg.contains("[models.reasoning]"));
        assert!(cfg.contains("max_parallel = 1"));
    }

    #[test]
    fn all_generated_configs_contain_required_sections() {
        for profile in [
            HardwareProfile::Desktop,
            HardwareProfile::Laptop,
            HardwareProfile::Headless,
        ] {
            let cfg = generate_config(&profile);
            assert!(cfg.contains("[server]"), "{profile} missing [server]");
            assert!(cfg.contains("[models.safety]"), "{profile} missing safety model");
            assert!(cfg.contains("[models.embeddings]"), "{profile} missing embeddings");
            assert!(cfg.contains("[[agents]]"), "{profile} missing agents");
            assert!(cfg.contains("[permissions.dev]"), "{profile} missing permissions");
            assert!(cfg.contains("[budget]"), "{profile} missing budget");
        }
    }
}
